### ISSUE TITLE
When you filter stats by colony it doesn't remove corps that you couldn't play with. This lowers my cofidence that you are actuallly filtering by expansion

### ISSUE THREAD

**Issue by Nathanpmyoung** [ssimeonoff/ssimeonoff.github.io#28]
I've set it to exclude colonies and yet Poseidon is still the top winrate.

![image](https://user-images.githubusercontent.com/20482100/106383230-ac42ea00-63bc-11eb-9078-afd965900a8f.png)

**Comment by PrismTank91** [comment]
I think that you didn't click on "Apply selected filters" because there are games on the list from excluded expansions.

I clicked on this button and apply same filters and everything looks correct.
![Zrzut ekranu 2021-02-04 121731](https://user-images.githubusercontent.com/78498842/106886086-c4c84280-66e3-11eb-942b-ba991d268238.png)

**Comment by ssimeonoff** [comment]
Yes, you changed the filters, but didn't apply the change.
