### ISSUE TITLE
Suggestion: Determine the winner at a draw

### ISSUE THREAD

**Issue by ap3h3ad** [ssimeonoff/ssimeonoff.github.io#8]
Hi,

i really like your tool and use it alot. I have a suggestion: In the last game two participants had the same amount of points and one only won because he had more megacredits. Could you implement a way to determine the winner in such a case, e.g. by asking explicitly for the winner if the case happens that two ore more of the players are tied?

Greetings!

**Comment by ssimeonoff** [comment]
That was discussed. on the forum.
One guy replied:
"I don't think it necessary, except perhaps for narcissistic reasons. The win percentage of any corporation aren't going to be effected in any real sense by these corner cases. Yes it will be somewhat overestimated since coming in second tied right now count as a win, but we're probably talking the second or third digit."

And I kind of agreed with that. The data shows the tied games are 1-2% only. Plus I don't know where and how to put the extra UI without messing up the Submit UI layout.
